### ISSUE TITLE
[user_notification] Test notification

### ISSUE THREAD

**Issue by IgnacioHeredia** [AI4EOSC/status#221]
```yaml
title:  Test title # notification title
summary: Bal bla **bla** bla _bla_ \n bla bla [link](https://www.google.com/) # short description of the notification
vo:  # vo to make the notifications to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
start: 2024-07-24T00:00:00.000Z  # start date where the notifcation will appear
end: 2024-08-01T00:00:00.000Z  # end date when the notfication will dissapear
```

_Put here additional information that won't be shown to users_
