### ISSUE TITLE
[user_notification] Test 1

### ISSUE THREAD

**Issue by MartaOB** [AI4EOSC/status#232]
```yaml
title:  notification title 1 | AI4EOSC
summary:  short description of the notification
vo: AI4EOSC
start: 2024-07-22T00:00:00.000Z
end: 2024-07-25T00:00:00.000Z
```

_Put here additional information that won't be shown to users_
