### ISSUE TITLE
[user_notification] Test 2

### ISSUE THREAD

**Issue by MartaOB** [AI4EOSC/status#233]
```yaml
title:  notification title 2 | iMagine
summary:  short description of the notification
vo: iMagine
start: 2024-07-22T00:00:00.000Z
end: 2024-07-25T00:00:00.000Z
```

_Put here additional information that won't be shown to users_
