### ISSUE TITLE
[user_notification] Test 3

### ISSUE THREAD

**Issue by MartaOB** [AI4EOSC/status#234]
```yaml
title:  popup title 3 | AI4EOSC & iMagine
summary:  short description of the popup
vo:
start: 2024-07-22T00:00:00.000Z
end: 2024-08-25T00:00:00.000Z
```

_Put here additional information that won't be shown to users_
