### ISSUE TITLE
[Notification] Notification Test

### ISSUE THREAD

**Issue by andresheca** [AI4EOSC/status#236]
```yaml
title:  # Notification test
summary:  Testing non critical notifications
vo: 
start: 2024-07-30T00:00:00.000Z 
end: 2024-08-30T00:00:00.000Z
```
