### ISSUE TITLE
[dashboard-notification] Test iMagine

### ISSUE THREAD

**Issue by MartaOB** [AI4EOSC/status#239]
```yaml
title: iMagine notification
summary:  
vo:  vo.imagine-ai.eu 
start: 2024-07-24T00:00:00.000Z  
end: 2024-08-24T00:00:00.000Z  
```

_Put here additional information that won't be shown to users_
