### ISSUE TITLE
[dashboard-notification] AI4EOSC test

### ISSUE THREAD

**Issue by MartaOB** [AI4EOSC/status#240]
```yaml
title:  AI4EOSC test notification 
summary:  additional info
vo:  vo.ai4eosc.eu
start: 2024-07-24T00:00:00.000Z  
end: 2024-08-24T00:00:00.000Z  
```

_Put here additional information that won't be shown to users_
