### ISSUE TITLE
[dashboard-notification] IFCA maintenance

### ISSUE THREAD

**Issue by IgnacioHeredia** [AI4EOSC/status#241]
```yaml
title:  Cluster maintenance
summary:  Around the 12th of September we scheduled a maintenance downtime for IFCA datacenters. Please make sure to backup your deployments to avoid losing data. 
vo:
start: 2024-08-20T00:00:00.000Z
end: 2024-09-16T00:00:00.000Z
```
