### ISSUE TITLE
[dashboard-popup] IFCA datacenters maintenance

### ISSUE THREAD

**Issue by IgnacioHeredia** [AI4EOSC/status#242]
```yaml
title:  ⚠️ Maintenance downtime is close! 
summary:  We have scheduled a maintenance downtime for Sept. 12th. Please backup your deployments to avoid losing data! 
vo:
start: 2024-09-05T00:00:00.000Z
end: 2024-09-16T00:00:00.000Z
```
