### ISSUE TITLE
[dashboard-notification] Test notification

### ISSUE THREAD

**Issue by MartaOB** [AI4EOSC/status#278]
```yaml
title:  Cluster maintenance
summary:  Around the 12th of September we scheduled a maintenance downtime for IFCA datacenters. Please make sure to backup your deployments to avoid losing data. 
vo:  vo.ai4eosc.eu # vo to show the notifications to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
start: 2024-08-20T00:00:00.000Z  # start date when the notification will appear
end: 2024-09-19T00:00:00.000Z  # end date when the notification will disappear
```

_Put here additional information that won't be shown to users_
