### ISSUE TITLE
[dashboard-popup] Popup test

### ISSUE THREAD

**Issue by MartaOB** [AI4EOSC/status#279]
```yaml
title:  ⚠️ Maintenance downtime is close! 
summary:  We have scheduled a maintenance downtime for Sept. 12th. Please backup your deployments to avoid losing data! 
vo:
start: 2024-09-05T00:00:00.000Z # bllablablabal
end: 2024-09-25T00:00:00.000Z # bllablablabal
```

_Put here additional information that won't be shown to users_
