### ISSUE TITLE
[dashboard-notification] Test Ai4eosc

### ISSUE THREAD

**Issue by MartaOB** [AI4EOSC/status#280]
```yaml
title: Test imagine # notification title
summary:  Test imagine # additional info
vo:  # vo to show the notifications to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
start: 2024-07-24T00:00:00.000Z  # start date when the notification will appear
end: 2024-09-24T00:00:00.000Z  # end date when the notification will disappear
```

_Put here additional information that won't be shown to users_
