### ISSUE TITLE
[dashboard-popup] IGNORE THIS: it is a test

### ISSUE THREAD

**Issue by MartaOB** [AI4EOSC/status#281]
```yaml
title:  Tes t# popup title
summary:  Test # additional info
vo: vo.ai4eosc.eu # vo to show the popup to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
start: 2024-07-24T00:00:00.000Z  # start date when the popup will appear
end: 2024-09-24T00:00:00.000Z  # end date when the popup will disappear
```

_Put here additional information that won't be shown to users_
