### ISSUE TITLE
[dashboard-popup] GPU nodes are down

### ISSUE THREAD

**Issue by IgnacioHeredia** [AI4EOSC/status#309]
```yaml
title:  Some GPUs might temporarily not be available
summary:  Due to a problem in the cluster, we needed to remove some GPU nodes. We will work on bringing them back as soon as possible.
vo:  # vo to show the notifications to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
start: 2024-11-05T00:00:00.000Z  # start date when the notification will appear
end: 2024-11-30T00:00:00.000Z  # end date when the notification will disappear
```

_Put here additional information that won't be shown to users_
