### ISSUE TITLE
[dashboard-popup] Cluster maintenance: 2nd December

### ISSUE THREAD

**Issue by IgnacioHeredia** [AI4EOSC/status#328]
```yaml
title: Cluster downtime: Monday 2nd December # notification title
summary: Please backup your data.  # additional info
vo:  # vo to show the notifications to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
start: 2024-11-28T00:00:00.000Z  # start date when the notification will appear
end: 2024-12-03T00:00:00.000Z  # end date when the notification will disappear
```

_Put here additional information that won't be shown to users_
