### ISSUE TITLE
[dashboard-notification] Schedule maintenance IFCA 2025/01/?

### ISSUE THREAD

**Issue by IgnacioHeredia** [AI4EOSC/status#356]
```yaml
title: Downtime expected during end of January # notification title
summary: As always, please back up you data # additional info
vo:  # vo to show the notifications to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
start: 2025-01-10T00:00:00.000Z  # start date when the notification will appear
end: 2025-01-30T00:00:00.000Z  # end date when the notification will disappear
```

_Put here additional information that won't be shown to users_
