### ISSUE TITLE
[dashboard-notification] CVAT upgrade

### ISSUE THREAD

**Issue by IgnacioHeredia** [AI4EOSC/status#375]
```yaml
title:  Manually backup CVAT data
summary:  "More information here: https://github.com/AI4EOSC/status/issues/375"
vo:  # vo to show the notifications to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
start: 2025-01-24T00:00:00.000Z  # start date when the notification will appear
end: 2025-02-03T00:00:00.000Z  # end date when the notification will disappear
```

Due to a bug in CVAT, we will upgrade the CVAT tool to the latest version (2.25). The upgrade will take place on **Monday 03th February**.

The new version is not compatible with your existing snapshots (see "Restore from snapshot" feature in [1]). So if you have existing data, you have to **manually** export them [2] and you will be able to import them back when we upgrade to the new version.

In summary, **before** Monday 3th February:

1. If you have important data saved in "snapshot-XYZ" you have to create a CVAT deployment restoring from "snapshot-XYZ". If you care about data of a already existing deployment, you can skip this step.
2. Manually export you data [2].

**After** Monday 03th February:

1. Create a new CVAT instance from scratch, without restoring from snapshot. To avoid confusions, delete you existing CVAT snapshots.
2. Manually import you data.
3. You are ready to annotate again
