### ISSUE TITLE
[dashboard-notification] ***

### ISSUE THREAD

**Issue by IgnacioHeredia** [AI4EOSC/status#381]
```yaml
title:  Cluster downtime on 23th February # notification title
summary: Please backup your data. https://docs.ai4eosc.eu/en/latest/help/faq.html#i-i-received-a-cluster-downtime-notification-what-should-i-do # additional info
vo:  # vo to show the notifications to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
start: 2025-02-15T00:00:00.000Z  # start date when the notification will appear
end: 2025-02-26T00:00:00.000Z  # end date when the notification will disappear
```

_Put here additional information that won't be shown to users_
