### ISSUE TITLE
[dashboard-popup] TUBITAK/INCD GPU maintenance

### ISSUE THREAD

**Issue by IgnacioHeredia** [AI4EOSC/status#414]
```yaml
title:  Nomad cluster maintenance
summary:  There will be a minor downtime on March 10 to update GPU nodes. Backup your deployments that landed on TUBITAK or INCD datacenters.
vo:  "vo.imagine-ai.eu"
start: 2024-03-05T00:00:00.000Z  # start date when the notification will appear
end: 2024-03-11T00:00:00.000Z  # end date when the notification will disappear
```
