### ISSUE TITLE
[nomad-maintenance] Test downtime for Nomad maintenance

### ISSUE THREAD

**Issue by MartaOB** [AI4EOSC/status#416]
```yaml
title:  Scheduled Nomad maintenance
datacenters:
    - "ifca-ai4eosc"
vo:  # vo to show the popup to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
downtimeStart: 2025-05-15T00:00:00.000Z  # start date when the maintenance will start
downtimeEnd: 2026-06-01T00:00:00.000Z  # end date when the maintenance will end
start: 2024-07-24T00:00:00.000Z  # start date when the notification will appear
end: 2026-01-01T00:00:00.000Z  # end date when the maintenance will end
```

_Put here additional information that won't be shown to users_
