### ISSUE TITLE
[nomad-maintenance] Test Dev: downtime for Nomad maintenance

### ISSUE THREAD

**Issue by MartaOB** [AI4EOSC/status#428]
```yaml
title:  Scheduled Nomad maintenance
summary:  There will be a minor downtime on March 10 to update GPU nodes. Backup your deployments that landed on TUBITAK or INCD datacenters.
datacenters:
    - "ifca-ai4eosc"
    - "ifca-imagine"
vo:  # vo to show the popup to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
downtimeStart: 2025-01-01T00:00:00.000Z  # start date when the maintenance will start
downtimeEnd: 2025-08-21T00:00:00.000Z  # end date when the maintenance will end
start: 2024-07-24T00:00:00.000Z  # start date when the notification will appear
end: 2026-08-24T00:00:00.000Z  # end date when the notification will disappear
```

_Put here additional information that won't be shown to users_
