### ISSUE TITLE
[dashboard-popup] Spain blackout

### ISSUE THREAD

**Issue by IgnacioHeredia** [AI4EOSC/status#467]
```yaml
title: Recovering from blackout # notification title
summary:  We are recovering from Spain/Portugal massive blackout, so expect some services to be down
vo:  # vo to show the popup to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
start: 2025-04-30T00:00:00.000Z  # start date when the popup will appear
end: 2025-06-10T00:00:00.000Z  # end date when the popup will disappear
```

_Put here additional information that won't be shown to users_
