### ISSUE TITLE
[dashboard-notification] Cluster restart

### ISSUE THREAD

**Issue by IgnacioHeredia** [AI4EOSC/status#485]
```yaml
title: Cluster restart # notification title
summary: We will restart the cluster on Wednesday morning to correct recent anomalies. # additional info
vo:  # vo to show the notifications to, comma-separated. eg: "vo.ai4eosc.eu, vo.imagine-ai.eu" - if empty show to everyone
start: 2025-05-12T00:00:00.000Z  # start date when the notification will appear
end: 2025-05-14T00:00:00.000Z  # end date when the notification will disappear
```

_Put here additional information that won't be shown to users_
